apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions-runner-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: github-actions-runner-operator
  template:
    metadata:
      labels:
        name: github-actions-runner-operator
    spec:
      serviceAccountName: github-actions-runner-operator
      containers:
        - name: github-actions-runner-operator
          image: garo:latest
          command:
          - github-actions-runner-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "github-actions-runner-operator"
