name: build
on: [pull_request, push]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    container: maven:3-jdk-14
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2
      - uses: franzdiebold/github-env-vars-action@v1.0.0
      - name: Run build
        run: |
          mvn clean install
