name: build
on: [push]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    #container: quay.io/quarkus/centos-quarkus-maven:20.0.0-java11
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2
      - uses: franzdiebold/github-env-vars-action@v1.0.0
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        # uses: docker://reviewdog/action-golangci-lint:v1 # pre-build docker image
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-go@v2
        with:
          go-version: '1.13.10'
      - name: Install operator SDK
        run: |
          sudo curl -Lo /usr/local/bin/operator-sdk https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
          sudo chmod a+x /usr/local/bin/operator-sdk
        env:
          RELEASE_VERSION: v0.17.0
      - name: build
        run:
          operator-sdk build github-actions-runner-operator:latest
      #- name: Create k8s Kind Cluster
      #  uses: helm/kind-action@v1.0.0-rc.1
      #  with:
      #    node_image: kindest/node:v1.17.2
      #- name: Install operator
      #  run: |
      #    # must force since we're off with the k8s version
      #    kubectl apply -f deploy/crds/garo.tietoevry.com_githubactionrunners_crd.yaml --validate=false
      #    kubectl apply -f deploy/
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: github-actions-runner-operator:latest
          registry: quay.io/evryfs
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
