name: build
on: [pull_request, push]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    #container: quay.io/quarkus/centos-quarkus-maven:19.3.1-java11
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2
      - uses: franzdiebold/github-env-vars-action@v1.0.0
      - name: Run build
        run: |
          docker build . -t garo
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.0.0-rc.1
        with:
          node_image: kindest/node:v1.18.0
      - name: Install operator
        run: |
          kubectl create deployment garo-operator --image=garo:latest
          sleep 3s
          kubectl logs -l app=garo-operator
